# Generated by Django 4.2.5 on 2023-09-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachmodel',
            old_name='degvee',
            new_name='degree',
        ),
    ]
