# Generated by Django 4.2.5 on 2023-09-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_rename_degvee_coachmodel_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilikmodels',
            name='Y_rasmi',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gyms')),
                ('trener_phone', models.CharField(default='', max_length=13)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.coachmodel')),
            ],
            options={
                'db_table': 'gyms',
            },
        ),
    ]
